I need build out linuxcncsvr first,so just wait...

diff --git a/scripts/linuxcnc.in b/scripts/linuxcnc.in
--- a/scripts/linuxcnc.in
+++ b/scripts/linuxcnc.in
@@ -26,6 +26,7 @@ KILL=@KILL@
 
 LINUXCNC_HOME=@EMC2_HOME@; export LINUXCNC_HOME
 LINUXCNC_BIN_DIR=@EMC2_BIN_DIR@
+LINUXCNC_FAKEBIN_DIR=@EMC2_FAKEBIN_DIR@
 LINUXCNC_TCL_DIR=@EMC2_TCL_DIR@
 LINUXCNC_HELP_DIR=@EMC2_HELP_DIR@
 LINUXCNC_RTLIB_DIR=@EMC2_RTLIB_DIR@
@@ -38,6 +39,7 @@ LINUXCNC_TCL_LIB_DIR=@EMC2_TCL_LIB_DIR@
 HALLIB_DIR=@HALLIB_DIR@; export HALLIB_DIR
 HALLIB_PATH=.:$HALLIB_DIR; export HALLIB_PATH
 PATH=$LINUXCNC_BIN_DIR:$PATH
+PATH=$LINUXCNC_FAKEBIN_DIR:$PATH
 [ -d $LINUXCNC_HOME/scripts ] && PATH=$LINUXCNC_HOME/scripts:$PATH
 
 if test "xyes" = "x@RUN_IN_PLACE@"; then
@@ -375,6 +377,112 @@ echo INIFILE="$INIFILE" >>$PRINT_FILE
 ################################################################################
 # 2.  extract info from the ini file that we will need later
 ################################################################################
+retval=
+
+# 2.1. define helper function
+function GetFromIniQuiet {
+    #$1 var name   $2 - section name
+    name=$1
+    retval=`$INIVAR -ini "$INIFILE" -var $1 -sec $2 2> /dev/null`
+    if [ ! -n "$1" ] ; then
+	exit -1
+    fi
+    echo "$name=$retval" >>$PRINT_FILE
+}
+
+function GetFromIni {
+    #$1 var name   $2 - section name
+    name=$1
+    retval=`$INIVAR -ini "$INIFILE" -var $1 -sec $2 2>>$DEBUG_FILE`
+    if [ ! -n "$1" ] ; then
+	echo "Can't find variable $1 in section [$2] of file $INIFILE."
+	exit -1
+    fi
+    echo "$name=$retval" >>$PRINT_FILE
+}
+
+function GetFromIniEx {
+    original_var="[$2]$1"
+    while [ $# -ge 2 ]; do
+	if retval=`$INIVAR -ini "$INIFILE" -var "$1" -sec "$2" 2>/dev/null`; then return; fi
+	shift 2
+    done
+    if [ $# -eq 0 ]; then
+	echo "Can't find $original_var in $INIFILE."
+	exit -1
+    fi
+    retval="$1"
+}
+
+# 2.2. get param file
+GetFromIni PARAMETER_FILE RS274NGC 
+RS274NGC_PARAMFILE=$retval
+
+# 2.3. get mot information
+GetFromIniEx MOT MOT EMCMOT EMCMOT motmod
+EMCMOT=$retval$MODULE_EXT # add module extension
+
+# 2.4. get io information
+GetFromIniEx IO IO EMCIO EMCIO io
+EMCIO=$retval
+
+# 2.5. get task information
+GetFromIni TASK TASK
+EMCTASK=$retval
+
+if [ "$EMCTASK" = emctask ]; then EMCTASK=linuxcnctask; fi
+
+# 2.6. we hardcode the server name, change if needed
+# linuxcncsvr now holds/creates all the NML channels,
+# so it needs to start by default, as the first process
+EMCSERVER=linuxcncsvr
+
+# 2.7. get halui information
+GetFromIniQuiet HALUI HAL
+HALUI=$retval
+
+# 2.9. get display information
+GetFromIni DISPLAY DISPLAY
+EMCDISPLAY=`(set -- $retval ; echo $1 )`
+EMCDISPLAYARGS=`(set -- $retval ; shift ; echo $* )`
+
+case $EMCDISPLAY in
+    tkemc) EMCDISPLAY=tklinuxcnc ;;
+    xemc) EMCDISPLAY=xlinuxcnc ;;
+esac
+
+# 2.10. get NML config information
+GetFromIniEx NML_FILE LINUXCNC NML_FILE EMC @DEFAULT_NMLFILE@
+NMLFILE=$retval
+export NMLFILE
+
+################################################################################
+# 3. Done gathering information, define a few functions
+# Execution resumes after function definitions...
+################################################################################
+
+KILL_TASK=
+KILL_TIMEOUT=20
+
+################################################################################
+# 3.1. Kills a list of tasks with timeout
+# if it doesn't work, kill -9 is used
+################################################################################
+function KillTaskWithTimeout() {
+    echo "kill task was called"
+}
+
+################################################################################
+# 3.2. define the cleanup function
+#
+# this cleanup function doesn't know or care what was actually
+# loaded - it simply kills _any_ processes in its list of
+# components
+################################################################################
+function Cleanup(){
+    rm -f $LOCKFILE;
+    return 0;
+}
 
 ################################################################################
 # 4. done with function definitions, execution resumes here
@@ -384,10 +492,6 @@ echo INIFILE="$INIFILE" >>$PRINT_FILE
 # to prevent multiple copies of controller
 LOCKFILE=/tmp/linuxcnc.lock
 
-function Cleanup(){
-    rm -f $LOCKFILE;
-    return 0;
-}
 
 # Check for lock file
 if [ -f $LOCKFILE ]; then
@@ -420,4 +524,22 @@ trap 'Cleanup ; exit 0' SIGINT SIGTERM
 # Create the lock file
 touch $LOCKFILE
 
+################################################################################
+# 4.1. pop up intro graphic
+################################################################################
+
+################################################################################
+# 4.2. Now we can finally start loading LinuxCNC
+################################################################################
+
+# 4.3.1. Run linuxcncserver in background, always (it owns/creates the NML buffers)
+echo "Starting LinuxCNC server program: $EMCSERVER" >>$PRINT_FILE
+if ! program_available $EMCSERVER; then
+    echo "Can't execute server program $EMCSERVER"
+    Cleanup
+    exit 1
+fi
+export INI_FILE_NAME="$INIFILE"
+$EMCSERVER -ini "$INIFILE" &
+sleep 1
 
